# Form implementation generated from reading ui file 'addbook.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc

class add_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 374)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_tile = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_tile.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_tile.setFont(font)
        self.lineEdit_tile.setObjectName("lineEdit_tile")
        self.verticalLayout.addWidget(self.lineEdit_tile)
        self.lineEdit_id = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_id.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.verticalLayout.addWidget(self.lineEdit_id)
        self.lineEdit_author = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_author.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_author.setFont(font)
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.verticalLayout.addWidget(self.lineEdit_author)
        self.lineEdit_publisher = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_publisher.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_publisher.setFont(font)
        self.lineEdit_publisher.setObjectName("lineEdit_publisher")
        self.verticalLayout.addWidget(self.lineEdit_publisher)
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(4, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color:rgb(141, 141, 141);\n"
"    color:white;\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(206, 206, 206);\n"
"}\n"                                      
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label_result = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.add_data)

    def add_data(self):
        try:
            database = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="library"
            )
            title = self.lineEdit_tile.text()
            id = self.lineEdit_id.text()
            author = self.lineEdit_author.text()
            publisher = self.lineEdit_publisher.text()

            if title == "" or id == "" or author == "" or publisher == "" :
                self.label_result.setText("Complete the Fields")
                self.label_result.setStyleSheet("color:red")
                return
            cursor = database.cursor()
            sqlf = "INSERT INTO l_data (title,id,author,publisher) VALUES (%s, %s, %s, %s)"
            value = (title,id,author,publisher)
            cursor.execute(sqlf,value)
            database.commit()
            self.label_result.setText('Added')
            self.label_result.setStyleSheet("color:green")
            self.lineEdit_id.setText("")
            self.lineEdit_author.setText("")
            self.lineEdit_tile.setText("")
            self.lineEdit_publisher.setText("")


        except mc.Error as e:
            self.label_result.setText('Failed To Enter Book Details')
            self.label_result.setStyleSheet("color:red")
            return

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit_tile.setPlaceholderText(_translate("Dialog", "Please Enter Book Title"))
        self.lineEdit_id.setPlaceholderText(_translate("Dialog", "Please Enter ID"))
        self.lineEdit_author.setPlaceholderText(_translate("Dialog", "Please Enter Author"))
        self.lineEdit_publisher.setPlaceholderText(_translate("Dialog", "Please Enter Publisher"))
        self.pushButton.setText(_translate("Dialog", "Insert Book"))



