# Form implementation generated from reading ui file 'insertmember.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc

class insert_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_id = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_id.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_id.setFont(font)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.verticalLayout.addWidget(self.lineEdit_id)
        self.lineEdit_name = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_name.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout.addWidget(self.lineEdit_name)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.pushButton_save = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_save.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setAutoFillBackground(False)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"    background-color:rgb(125, 125, 125);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:black;\n"
"    color:white\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout.addWidget(self.pushButton_save)
        self.label_result = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton_save.clicked.connect(self.addmember)
    def addmember(self):
        try:
            database = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="library"

            )
            id = self.lineEdit_id.text()
            name = self.lineEdit_name.text()
            mobile = self.lineEdit_3.text()
            email = self.lineEdit_4.text()
            cursor = database.cursor()
            if id == "" or name == "" or mobile == "" or cursor == "":
                self.label_result.setText("Empty Fields")
                self.label_result.setStyleSheet("color:red")
                return
            sql = "INSERT INTO member (id,name,mobile,email) VALUES (%s,%s,%s,%s)"
            values = (id,name,mobile,email)
            cursor.execute(sql,values)
            database.commit()
            self.label_result.setText("Added")
            self.label_result.setStyleSheet("color:green")
            self.lineEdit_id.setText("")
            self.lineEdit_name.setText("")
            self.lineEdit_3.setText("")
            self.lineEdit_4.setText("")
        except mc.Error as e:
            self.label_result.setText("Error Inserting Data")
            self.label_result.setStyleSheet("color:red")


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Insert Member"))
        self.lineEdit_id.setPlaceholderText(_translate("Dialog", "Please Enter Member ID"))
        self.lineEdit_name.setPlaceholderText(_translate("Dialog", "Please Enter Member Name"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Please Enter Member Mobile"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Please Enter Member Email"))
        self.pushButton_save.setText(_translate("Dialog", "Insert Member"))

